# == mcarvalhor ==

<VirtualHost *:80>
        ServerName mcarvalhor.com
        ServerAlias www.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/www.mcarvalhor.com
</VirtualHost>

<VirtualHost *:80>
        ServerName admin.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/admin.mcarvalhor.com
</VirtualHost>

<VirtualHost *:80>
        ServerName internetsoftwareconnect.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/internetsoftwareconnect.mcarvalhor.com
</VirtualHost>

<VirtualHost *:80>
        ServerName resources.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/resources.mcarvalhor.com
</VirtualHost>


# vim: syntax=apache ts=4 sw=4 sts=4 sr noet