# == mcarvalhor ==

<Directory /doc_root>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

<VirtualHost *:443>
        ServerName mcarvalhor.com
        ServerAlias www.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/www.mcarvalhor.com
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/cloudflare.crt
        SSLCertificateKeyFile /etc/apache2/ssl/cloudflare.key
        php_flag display_errors Off
        php_flag display_startup_errors Off
        php_flag log_errors On
        php_value error_reporting 32767
</VirtualHost>

<VirtualHost *:443>
        ServerName admin.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/admin.mcarvalhor.com
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/cloudflare.crt
        SSLCertificateKeyFile /etc/apache2/ssl/cloudflare.key
        php_flag display_errors Off
        php_flag display_startup_errors Off
        php_flag log_errors On
        php_value error_reporting 32767
</VirtualHost>

<VirtualHost *:443>
        ServerName internetsoftwareconnect.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/internetsoftwareconnect.mcarvalhor.com
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/cloudflare.crt
        SSLCertificateKeyFile /etc/apache2/ssl/cloudflare.key
        php_flag display_errors Off
        php_flag display_startup_errors Off
        php_flag log_errors On
        php_value error_reporting 32767
</VirtualHost>

<VirtualHost *:443>
        ServerName resources.mcarvalhor.com
        ServerAdmin webmaster@localhost
        DocumentRoot /doc_root/resources.mcarvalhor.com
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/cloudflare.crt
        SSLCertificateKeyFile /etc/apache2/ssl/cloudflare.key
        php_flag display_errors Off
        php_flag display_startup_errors Off
        php_flag log_errors On
        php_value error_reporting 32767
</VirtualHost>


# vim: syntax=apache ts=4 sw=4 sts=4 sr noet